### ISSUE TITLE
Check if Member leaves organisation and pull role permissions?

### ISSUE THREAD

**Issue by kmzkamikaze** [mobiglas/sc-janus#1]
Just wanna say we love the discord bot, makes it easy for people to get access to right role while no one online can do it...

but there is one issue tho, when members leave the organisation, it won't remove roles from discord... So my thought was if could possibly add a command for it or make it automatically check every hour or so?

**Comment by mobiglas** [comment]
It cannot be done, at least not in the current implementation.
There is no persistent storage that can be used to trace a discord user to a StarCitizen user.

So it needs some serious coding and a database before this feature. 

PS: sorry for the delay, it seems there are no email notifications for issues :(
